lmachens/arkesia.gg-web

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/routes/maps/$continent.$area.tsx, app/styles/global.css, prisma/schema.prisma
**Breaking**
This request changes the database schema. You need to clear or update your nodes.
`name`, `description` and `screenshot` added to node schema.
`name` and `description` are already implemented in the form and node details.
`screenshot` will be added in #2.
The form is too big now, but this will be fixed in #5
=> ✨ Add name and description properties

.gitignore, README.md
- Added `/api/_build` to `.gitignore`
- Added some  instructions for getting Screenshot upload working locally with Supabase
=> 📝 Update ReadMe with Supabase instructions

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/lib/validation.ts, app/routes/maps/$continent.$area.tsx
=> 🐛 Add character limit to titles and description

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx
=> 🐛 Fix opening multiple drawers

app/components/DraggableMarker.tsx
=> 🐛 Clear screenshot after saving node

app/components/DraggableMarker.tsx, app/components/ImageDropzone.tsx
=> ✨ Add button to clear screenshot

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/lib/discord.ts, app/lib/validation.ts, package-lock.json, package.json
Fixes #20
The editor allows us to extend the functionality in upcoming releases:
https://mantine.dev/others/rte/
=> ✨ Formatting in node description

app/components/ImagePreview.tsx, app/components/MapView.client.tsx, app/lib/discord.ts, app/routes/maps/$continent.$area.tsx
=> ✨ Add expanded image view

app/components/CanvasMarker.tsx, app/components/MapView.client.tsx, app/components/includeCanvasTileLayer.ts, package-lock.json, package.json
=> ✨ Rotate maps to match in-game maps

app/components/DraggableMarker.tsx, app/components/ImageDropzone.tsx
=> ✨ Allow paste screenshot from clipboard

app/components/DraggableMarker.tsx, app/components/MapSelect.tsx, app/components/TileControl.tsx, app/components/TypeItem.tsx, app/lib/static.ts
I removed custom icons and optimized select elements
=> ✨ Use original map icons

.eslintrc.js, app/components/CanvasMarker.tsx, app/components/DraggableMarker.tsx, app/components/ImageDropzone.tsx, app/components/ImageUploadIcon.tsx, app/components/MapView.client.tsx, app/components/TileControl.tsx, app/components/TypeItem.tsx, app/lib/db.server.ts, app/lib/discord.ts, app/lib/map.ts, app/lib/static.ts, app/lib/validation.ts, app/routes/maps/$continent.$area.tsx, app/routes/maps/$continent.tsx, package-lock.json, package.json
- Please call `npm install` to install latest dependencies including ESLint.
- All dependencies are updated to latest version.
- Add recommended ESLint config and fix issues
=> ✨ Add and apply ESLint rules

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/components/NodeDetails.tsx
=> ✨ Make interacting possible while drawer is opened

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/components/NodeDescription.tsx, app/components/NodeDetails.tsx, app/lib/static.ts, app/lib/types.ts, app/routes/maps/$continent.$area.tsx, package-lock.json, package.json
This allows us to create links to maps and nodes.
I added a link to one of the portals to link to a different map.
=> ✨ Load tile and node from URL

app/components/AppHeader.tsx, app/components/DraggableMarker.tsx, app/components/IconMarker.tsx, app/components/MapSelect.tsx, app/components/MapView.client.tsx, app/components/NodeDetails.tsx, app/components/TileControl.tsx, app/lib/actions.server.ts, app/lib/discord.ts, app/lib/validation.ts, app/routes/maps/$continent.$area.tsx, app/routes/maps/$continent.tsx, app/styles/global.css, prisma/migrations/20220304111320_make_user_id_optional/migration.sql, prisma/migrations/20220304114751_make_name_optional/migration.sql, prisma/schema.prisma
=> ✨ Add unverified nodes and report content

app/components/AppHeader.tsx, app/components/DiscoveredNodes.tsx, app/components/NodeDetails.tsx, app/components/Settings.tsx, app/components/TileControl.tsx, app/lib/store.ts, app/routes/maps/$continent.$area.tsx, package-lock.json, package.json
=> ✨ Hide Discovered Content

app/components/DraggableMarker.tsx, app/components/IconMarker.tsx, app/components/TileControl.tsx, app/lib/static.ts, app/lib/store.ts
and remember last selected node type
=> ♻️ Remove duplicate node names

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/components/TileControl.tsx, app/lib/static.ts, app/routes/index.tsx, app/routes/maps/$continent.$area.tsx
- World map
- Center map on change
=> ✨ Add world map

app/lib/static.ts
I couldn't find the icons and created them by hand based on:
https://game-icons.net/1x1/lorc/conversation.html
https://game-icons.net/1x1/delapouite/cooking-pot.html
https://game-icons.net/1x1/lorc/lightning-tear.html
=> ✨ Add Cooking, Hidden Story and Vista

app/lib/static.ts
I would like to separate some of the icons a bit more but this is ok for a first phase.
=> Organise / Rename Icons v1

app/lib/validation.ts
=> 🐛 Increase max node name length

app/components/NodeDescription.tsx, app/styles/global.css
=> 🐛 Fix node description wrapping

app/components/NodeDescription.tsx, app/components/NodeDetails.tsx
=> 🐛 Remove description truncated

app/lib/actions.server.ts, app/lib/storage.server.ts
=> 🐛 Crashing when updating an screenshot

app/components/DraggableMarker.tsx, app/components/NodeDetails.tsx, app/components/Settings.tsx, app/components/TileControl.tsx, app/lib/store.ts
=> ✨ Add button to toggle drawer position left/right

app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/components/NodeDetails.tsx, app/components/TileControl.tsx, app/lib/db.server.ts, app/lib/static.ts, app/lib/types.ts, app/routes/maps/$continent.$area.tsx, prisma/migrations/20220311094124_add_transit_to_id/migration.sql, prisma/schema.prisma
- Right-click on a node transits to target node
- Display node ID in drawer
- run `npx prisma generate` and `npx prisma migrate` for migrating to new database schema
=> ✨ Transit to node on right-click

app/components/MapSelect.tsx, app/components/MapView.client.tsx, app/routes/index.tsx, app/routes/maps/$continent.tsx
There was a crash if you access a region with invalid tile ID.
=> 🐛 Fix tile load by id

app/lib/static.ts
=> 🐛 Fix Toxiclaw Cavern and Feiton Varukas tiles

app/lib/static.ts
Another Story:
https://game-icons.net/1x1/lorc/book-cover.html
Secret Passage:
https://game-icons.net/1x1/delapouite/secret-door.html
Secret Mechanics:
https://game-icons.net/1x1/lorc/lever.html
Music:
https://game-icons.net/1x1/lorc/double-quaver.html
=> ✨ Add Another Story, Secret Passage, Secret Mechanics, Music

app/components/ActionIcons.tsx, app/components/AppSpotlightProvider.tsx, app/components/DraggableMarker.tsx, app/components/MapView.client.tsx, app/components/TileControl.tsx, app/lib/store.ts, app/routes/maps/$continent.$area.tsx
=> Rework right-click to create new nodes

app/components/MapView.client.tsx, app/components/TileControl.tsx, app/components/TypeSelect.tsx, app/components/UpsertMarker.tsx, package-lock.json, package.json
=> ✨ Rework type selection on new node

app/components/ActionIcons.tsx, app/components/IconMarker.tsx, app/components/TileControl.tsx, app/lib/store.ts, app/styles/global.css
=> ✨ Display names on map without hover

app/components/ActionIcons.tsx, app/components/IconMarker.tsx, app/lib/store.ts
=> ✨ Allow to resize icons

app/components/AvailableNodes.tsx, app/lib/loaders.server.ts, app/lib/loaders.ts
=> 🐛 Fix node summary

app/components/MapView.client.tsx, app/components/TileControl.tsx
=> ✨ Right click go one up in hierarchy

.gitignore, app/components/ActionIcons.tsx, app/components/AvailableNodes.tsx, app/components/IconMarker.tsx, app/components/MapView.client.tsx, app/components/NodeDetails.tsx, app/components/TileControl.tsx, app/components/UpsertMarker.tsx, app/lib/actions.server.ts, app/lib/db.server.ts, app/lib/discord.ts, app/lib/loaders.server.ts, app/lib/loaders.ts, app/lib/store.ts, app/lib/supabase.ts, app/lib/types.ts, app/lib/validation.ts, prisma/migrations/20220325084608_node_locations/migration.sql, prisma/schema.prisma, supabase/config.toml
**Breaking change**
The database schema changed
**What's changed?**
A node can have multiple locations now. Moderators can add new locations by opening the create node form and select the ID of an existing node.
=> ✨ Support multiple locations for a node

app/components/AppSpotlightProvider.tsx, app/components/IconMarker.tsx, app/components/MapView.client.tsx, app/components/TileControl.tsx, app/lib/discord.ts, app/lib/supabase.ts, app/styles/global.css
=> Location links

app/root.tsx, app/routes/maps/$continent.$area.tsx
https://remix.run/docs/en/v1/api/conventions#unstable_shouldreload
=> ⚡️ Reduce number of reloads

README.md, app/lib/static.ts, app/lib/storage.server.ts
=> Tortoyk map issues

app/lib/static.ts
=> Missing marker types

app/components/AppSpotlightProvider.tsx, app/lib/supabase.ts
=> ✨Exclude map transitions and stairs in search

app/components/AvailableNodes.tsx, app/components/NodeDetails.tsx, app/lib/supabase.ts
=> Optimizing Node Summary

app/lib/static.ts
=> ✨ Add Abyss Raid & Story Mission Icons

app/lib/static.ts, app/lib/supabase.ts, app/lib/types.ts
=> ✨ Exclude World Areas in node summary

app/components/TileControl.tsx
=> ✨ World map links do not focus nodes on maps

app/components/MapView.client.tsx, app/lib/static.ts
=> 🐛 Remove broken/wrong tiles from islands

app/lib/static.ts
=> ✨ Add node for Unique Monsters

app/components/MapView.client.tsx
=> ✨ Optimize zoom functionality

app/components/IconMarker.tsx, app/lib/static.ts, app/lib/types.ts, app/styles/global.css
=> ✨ Optimize visibility of nodes and names

app/lib/static.ts
=> 🐛 Fix category of Gold Named Enemy and Unique Monster

app/lib/static.ts
=> ✨ Add Cradle of the Sea Fermata

app/components/NodeDetails.tsx, app/components/UpsertMarker.tsx
=> 🐛 Fix switching to main layer after node change

app/components/ActionIcons.tsx, app/components/DiscoveredNodes.tsx, app/lib/store.ts
=> ✨ Import and export discovered nodes

app/components/Notifications.tsx, app/root.tsx
=> ✨ Add notification to join the team

app/components/IslandGuideLink.tsx, app/components/NodeDetails.tsx
=> ✨ Add island guides links to Maxroll

app/lib/actions.server.ts, app/lib/db.server.ts, app/lib/storage.server.ts
=> 🐛 Node titles and descriptions changes don't get saved

app/components/ActionIcons.tsx, app/components/FiltersSelect.tsx, app/components/IslandGuideLink.tsx, app/components/NodeDetails.tsx, app/lib/static.ts
=> Island guide links

app/components/NodeDetails.tsx, app/components/ShareButton.tsx
=> ✨ Add share link to node details
